Failure # 1 (occurred at 2024-05-31_11-11-21)
[36mray::ImplicitFunc.train()[39m (pid=959296, ip=129.69.82.151, actor_id=a5133a85838ce86b299909c001000000, repr=func)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/robert/Volume/Forschungsarbeit_Robert_Asmussen/05_Data/miniconda3/envs/trxenv/lib/python3.11/site-packages/ray/tune/trainable/trainable.py", line 331, in train
    raise skipped from exception_cause(skipped)
  File "/media/robert/Volume/Forschungsarbeit_Robert_Asmussen/05_Data/miniconda3/envs/trxenv/lib/python3.11/site-packages/ray/air/_internal/util.py", line 98, in run
    self._ret = self._target(*self._args, **self._kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/robert/Volume/Forschungsarbeit_Robert_Asmussen/05_Data/miniconda3/envs/trxenv/lib/python3.11/site-packages/ray/tune/trainable/function_trainable.py", line 45, in <lambda>
    training_func=lambda: self._trainable_func(self.config),
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/robert/Volume/Forschungsarbeit_Robert_Asmussen/05_Data/miniconda3/envs/trxenv/lib/python3.11/site-packages/ray/tune/trainable/function_trainable.py", line 248, in _trainable_func
    output = fn()
             ^^^^
  File "/media/robert/Volume/Forschungsarbeit_Robert_Asmussen/05_Data/TRX/tuning.py", line 167, in train_cifar
    task_loss, task_accuracy = train_task(task_dict, model, config["tasks_per_batch"], device)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/robert/Volume/Forschungsarbeit_Robert_Asmussen/05_Data/TRX/tuning.py", line 238, in train_task
    task_loss.backward(retain_graph=False)
  File "/media/robert/Volume/Forschungsarbeit_Robert_Asmussen/05_Data/miniconda3/envs/trxenv/lib/python3.11/site-packages/torch/_tensor.py", line 525, in backward
    torch.autograd.backward(
  File "/media/robert/Volume/Forschungsarbeit_Robert_Asmussen/05_Data/miniconda3/envs/trxenv/lib/python3.11/site-packages/torch/autograd/__init__.py", line 267, in backward
    _engine_run_backward(
  File "/media/robert/Volume/Forschungsarbeit_Robert_Asmussen/05_Data/miniconda3/envs/trxenv/lib/python3.11/site-packages/torch/autograd/graph.py", line 744, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR
